# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.AccountSignaturesInformation do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :accountSignatures
  ]

  @type t :: %__MODULE__{
          :accountSignatures => [AccountSignature]
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.AccountSignaturesInformation do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:accountSignatures, :list, DocuSign.Model.AccountSignature, options)
  end
end
