# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.AccountIdentityVerificationWorkflow do
  @moduledoc """
  Specifies an Identity Verification workflow.
  """

  @derive [Poison.Encoder]
  defstruct [
    :defaultDescription,
    :defaultName,
    :inputOptions,
    :signatureProvider,
    :workflowId,
    :workflowResourceKey
  ]

  @type t :: %__MODULE__{
          :defaultDescription => String.t(),
          :defaultName => String.t(),
          :inputOptions => [AccountIdentityInputOption],
          :signatureProvider => AccountSignatureProvider,
          :workflowId => String.t(),
          :workflowResourceKey => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.AccountIdentityVerificationWorkflow do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :inputOptions,
      :list,
      DocuSign.Model.AccountIdentityInputOption,
      options
    )
    |> deserialize(
      :signatureProvider,
      :struct,
      DocuSign.Model.AccountSignatureProvider,
      options
    )
  end
end
