# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.AccountSeals do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :seals
  ]

  @type t :: %__MODULE__{
          :seals => [SealIdentifier]
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.AccountSeals do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:seals, :list, DocuSign.Model.SealIdentifier, options)
  end
end
