# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.BccEmailArchiveList do
  @moduledoc """
  Contains a list of BCC email archive configurations.
  """

  @derive [Poison.Encoder]
  defstruct [
    :bccEmailArchives,
    :endPosition,
    :nextUri,
    :previousUri,
    :resultSetSize,
    :startPosition,
    :totalSetSize
  ]

  @type t :: %__MODULE__{
          :bccEmailArchives => [BccEmailArchive],
          :endPosition => String.t(),
          :nextUri => String.t(),
          :previousUri => String.t(),
          :resultSetSize => String.t(),
          :startPosition => String.t(),
          :totalSetSize => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.BccEmailArchiveList do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:bccEmailArchives, :list, DocuSign.Model.BccEmailArchive, options)
  end
end
