# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.BccEmailArchiveHistoryList do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :bccEmailArchiveHistory,
    :endPosition,
    :nextUri,
    :previousUri,
    :resultSetSize,
    :startPosition,
    :totalSetSize
  ]

  @type t :: %__MODULE__{
          :bccEmailArchiveHistory => [BccEmailArchiveHistory],
          :endPosition => String.t(),
          :nextUri => String.t(),
          :previousUri => String.t(),
          :resultSetSize => String.t(),
          :startPosition => String.t(),
          :totalSetSize => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.BccEmailArchiveHistoryList do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :bccEmailArchiveHistory,
      :list,
      DocuSign.Model.BccEmailArchiveHistory,
      options
    )
  end
end
