# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.BulkSendErrorStatus do
  @moduledoc """
  A single bulk send error report.
  """

  @derive [Poison.Encoder]
  defstruct [
    :created,
    :errorMessage,
    :recipientEmails
  ]

  @type t :: %__MODULE__{
          :created => String.t(),
          :errorMessage => String.t(),
          :recipientEmails => [String.t()]
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.BulkSendErrorStatus do
  def decode(value, _options) do
    value
  end
end
