# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.BulkSendBatchSummary do
  @moduledoc """
  Summary status of a single batch.
  """

  @derive [Poison.Encoder]
  defstruct [
    :batchId,
    :batchName,
    :batchSize,
    :batchUri,
    :failed,
    :queued,
    :sent,
    :submittedDate
  ]

  @type t :: %__MODULE__{
          :batchId => String.t(),
          :batchName => String.t(),
          :batchSize => String.t(),
          :batchUri => String.t(),
          :failed => String.t(),
          :queued => String.t(),
          :sent => String.t(),
          :submittedDate => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.BulkSendBatchSummary do
  def decode(value, _options) do
    value
  end
end
