# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.BulkSend do
  @moduledoc """
  The bulk send list resource provides methods that enable you to create and manage bulk sending lists, which you can use to send multiple copies of an envelope in a single batch.   **Note**: The Bulk Send feature is only available on Business Pro plans that are using EasySign.
  """

  @derive [Poison.Encoder]
  defstruct [
    :bulkCopies,
    :listId,
    :name
  ]

  @type t :: %__MODULE__{
          :bulkCopies => [BulkSendingCopy],
          :listId => String.t(),
          :name => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.BulkSend do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:bulkCopies, :list, DocuSign.Model.BulkSendingCopy, options)
  end
end
