# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.BulkSendingListSummary do
  @moduledoc """
  This object contains basic information about a bulk send list.
  """

  @derive [Poison.Encoder]
  defstruct [
    :bulkSendListId,
    :createdByUser,
    :createdDate,
    :name
  ]

  @type t :: %__MODULE__{
          :bulkSendListId => String.t(),
          :createdByUser => String.t(),
          :createdDate => String.t(),
          :name => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.BulkSendingListSummary do
  def decode(value, _options) do
    value
  end
end
