# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.BulkSendingList do
  @moduledoc """
  This object contains the details for the bulk send list.
  """

  @derive [Poison.Encoder]
  defstruct [
    :bulkCopies,
    :listId,
    :name
  ]

  @type t :: %__MODULE__{
          :bulkCopies => [BulkSendingCopy],
          :listId => String.t(),
          :name => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.BulkSendingList do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:bulkCopies, :list, DocuSign.Model.BulkSendingCopy, options)
  end
end
