# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.BulkSendBatchStatus do
  @moduledoc """
  Result of &#x60;getBulkSendBatchStatus&#x60;
  """

  @derive [Poison.Encoder]
  defstruct [
    :batchId,
    :batchName,
    :batchSize,
    :bulkErrors,
    :envelopeIdOrTemplateId,
    :envelopesUri,
    :failed,
    :mailingListId,
    :ownerUserId,
    :queued,
    :senderUserId,
    :sent,
    :submittedDate
  ]

  @type t :: %__MODULE__{
          :batchId => String.t(),
          :batchName => String.t(),
          :batchSize => String.t(),
          :bulkErrors => [BulkSendErrorStatus],
          :envelopeIdOrTemplateId => String.t(),
          :envelopesUri => String.t(),
          :failed => String.t(),
          :mailingListId => String.t(),
          :ownerUserId => String.t(),
          :queued => String.t(),
          :senderUserId => String.t(),
          :sent => String.t(),
          :submittedDate => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.BulkSendBatchStatus do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:bulkErrors, :list, DocuSign.Model.BulkSendErrorStatus, options)
  end
end
