# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.BulkSendingCopyTab do
  @moduledoc """
  A tab associated with the bulk send recipient. In a bulk send request, each recipient tab must match a recipient tab on the envelope or template that you want to send. To match up, the &#x60;tabLabel&#x60; for this tab and the &#x60;tabLabel&#x60; for the corresponding tab on the envelope or template must be the same.  For example, if the envelope has a placeholder text tab with the &#x60;tabLabel&#x60; &#x60;childName&#x60;, you must assign the same &#x60;tabLabel&#x60; &#x60;childName&#x60; to the tab here that you are populating with that information.
  """

  @derive [Poison.Encoder]
  defstruct [
    :initialValue,
    :tabLabel
  ]

  @type t :: %__MODULE__{
          :initialValue => String.t(),
          :tabLabel => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.BulkSendingCopyTab do
  def decode(value, _options) do
    value
  end
end
