# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.Comments do
  @moduledoc """
  Details about envelope comments.
  """

  @derive [Poison.Encoder]
  defstruct [
    :envelopeId,
    :hmac,
    :id,
    :mentions,
    :read,
    :sentByEmail,
    :sentByFullName,
    :sentByImageId,
    :sentByInitials,
    :sentByRecipientId,
    :sentByUserId,
    :signingGroupId,
    :signingGroupName,
    :subject,
    :tabId,
    :text,
    :threadId,
    :threadOriginatorId,
    :timestamp,
    :timeStampFormatted,
    :visibleTo
  ]

  @type t :: %__MODULE__{
          :envelopeId => String.t(),
          :hmac => String.t(),
          :id => String.t(),
          :mentions => [String.t()],
          :read => boolean(),
          :sentByEmail => String.t(),
          :sentByFullName => String.t(),
          :sentByImageId => String.t(),
          :sentByInitials => String.t(),
          :sentByRecipientId => String.t(),
          :sentByUserId => String.t(),
          :signingGroupId => String.t(),
          :signingGroupName => String.t(),
          :subject => String.t(),
          :tabId => String.t(),
          :text => String.t(),
          :threadId => String.t(),
          :threadOriginatorId => String.t(),
          :timestamp => String.t(),
          :timeStampFormatted => String.t(),
          :visibleTo => [String.t()]
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.Comments do
  def decode(value, _options) do
    value
  end
end
