# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.CommentsPublish do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :commentsToPublish
  ]

  @type t :: %__MODULE__{
          :commentsToPublish => [CommentPublish]
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.CommentsPublish do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:commentsToPublish, :list, DocuSign.Model.CommentPublish, options)
  end
end
