# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.ConditionalRecipientRule do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :conditions,
    :order,
    :recipientGroup,
    :recipientId
  ]

  @type t :: %__MODULE__{
          :conditions => [ConditionalRecipientRuleCondition],
          :order => String.t(),
          :recipientGroup => RecipientGroup,
          :recipientId => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.ConditionalRecipientRule do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :conditions,
      :list,
      DocuSign.Model.ConditionalRecipientRuleCondition,
      options
    )
    |> deserialize(:recipientGroup, :struct, DocuSign.Model.RecipientGroup, options)
  end
end
