# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.ConnectSalesforceField do
  @moduledoc """
  This object is used to match a DocuSign field to a Salesforce field so that Docusign can send information to your Salesforce account.
  """

  @derive [Poison.Encoder]
  defstruct [
    :dsAttribute,
    :dsLink,
    :dsNode,
    :id,
    :sfField,
    :sfFieldName,
    :sfFolder,
    :sfLockedValue
  ]

  @type t :: %__MODULE__{
          :dsAttribute => String.t(),
          :dsLink => String.t(),
          :dsNode => String.t(),
          :id => String.t(),
          :sfField => String.t(),
          :sfFieldName => String.t(),
          :sfFolder => String.t(),
          :sfLockedValue => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.ConnectSalesforceField do
  def decode(value, _options) do
    value
  end
end
