# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.ContactModRequest do
  @moduledoc """
  The request object containing the new information for the contacts.
  """

  @derive [Poison.Encoder]
  defstruct [
    :contactList
  ]

  @type t :: %__MODULE__{
          :contactList => [Contact]
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.ContactModRequest do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:contactList, :list, DocuSign.Model.Contact, options)
  end
end
