# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.DateStampProperties do
  @moduledoc """
  Specifies the area in which a date stamp is placed. This parameter uses pixel positioning to draw a rectangle at the center of the stamp area. The stamp is superimposed on top of this central area.  This property contains the following information about the central rectangle:  - &#x60;DateAreaX&#x60;: The X axis position of the top-left corner. - &#x60;DateAreaY&#x60;: The Y axis position of the top-left corner. - &#x60;DateAreaWidth&#x60;: The width of the rectangle. - &#x60;DateAreaHeight&#x60;: The height of the rectangle.
  """

  @derive [Poison.Encoder]
  defstruct [
    :dateAreaHeight,
    :dateAreaWidth,
    :dateAreaX,
    :dateAreaY
  ]

  @type t :: %__MODULE__{
          :dateAreaHeight => String.t(),
          :dateAreaWidth => String.t(),
          :dateAreaX => String.t(),
          :dateAreaY => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.DateStampProperties do
  def decode(value, _options) do
    value
  end
end
