# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.DowngradRequestBillingInfoResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :downgradePlanInformation,
    :paymentMethod
  ]

  @type t :: %__MODULE__{
          :downgradePlanInformation => DowngradePlanUpdateResponse,
          :paymentMethod => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.DowngradRequestBillingInfoResponse do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :downgradePlanInformation,
      :struct,
      DocuSign.Model.DowngradePlanUpdateResponse,
      options
    )
  end
end
