# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.EnvelopeTransferRuleRequest do
  @moduledoc """
  This object contains details about the envelope transfer rule that you want to create.
  """

  @derive [Poison.Encoder]
  defstruct [
    :carbonCopyOriginalOwner,
    :enabled,
    :envelopeTransferRuleId,
    :eventType,
    :fromGroups,
    :fromUsers,
    :modifiedDate,
    :modifiedUser,
    :toFolder,
    :toUser
  ]

  @type t :: %__MODULE__{
          :carbonCopyOriginalOwner => String.t(),
          :enabled => String.t(),
          :envelopeTransferRuleId => String.t(),
          :eventType => String.t(),
          :fromGroups => [Group],
          :fromUsers => [UserInformation],
          :modifiedDate => String.t(),
          :modifiedUser => UserInformation,
          :toFolder => Folder,
          :toUser => UserInformation
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.EnvelopeTransferRuleRequest do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:fromGroups, :list, DocuSign.Model.Group, options)
    |> deserialize(:fromUsers, :list, DocuSign.Model.UserInformation, options)
    |> deserialize(:modifiedUser, :struct, DocuSign.Model.UserInformation, options)
    |> deserialize(:toFolder, :struct, DocuSign.Model.Folder, options)
    |> deserialize(:toUser, :struct, DocuSign.Model.UserInformation, options)
  end
end
