# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.EnvelopeSummary do
  @moduledoc """
   This object describes an envelope.
  """

  @derive [Poison.Encoder]
  defstruct [
    :bulkEnvelopeStatus,
    :envelopeId,
    :errorDetails,
    :status,
    :statusDateTime,
    :uri
  ]

  @type t :: %__MODULE__{
          :bulkEnvelopeStatus => BulkEnvelopeStatus,
          :envelopeId => String.t(),
          :errorDetails => ErrorDetails,
          :status => String.t(),
          :statusDateTime => String.t(),
          :uri => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.EnvelopeSummary do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :bulkEnvelopeStatus,
      :struct,
      DocuSign.Model.BulkEnvelopeStatus,
      options
    )
    |> deserialize(:errorDetails, :struct, DocuSign.Model.ErrorDetails, options)
  end
end
