# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.EnvelopeWorkflowDefinition do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :currentWorkflowStepId,
    :workflowStatus,
    :workflowSteps
  ]

  @type t :: %__MODULE__{
          :currentWorkflowStepId => String.t(),
          :workflowStatus => String.t(),
          :workflowSteps => [WorkflowStep]
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.EnvelopeWorkflowDefinition do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:workflowSteps, :list, DocuSign.Model.WorkflowStep, options)
  end
end
