# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.EnvelopeTransferRule do
  @moduledoc """
  This object contains details about an envelope transfer rule.
  """

  @derive [Poison.Encoder]
  defstruct [
    :carbonCopyOriginalOwner,
    :enabled,
    :envelopeTransferRuleId,
    :eventType,
    :fromGroup,
    :fromUser,
    :modifiedDate,
    :modifiedUser,
    :toFolder,
    :toUser
  ]

  @type t :: %__MODULE__{
          :carbonCopyOriginalOwner => String.t(),
          :enabled => String.t(),
          :envelopeTransferRuleId => String.t(),
          :eventType => String.t(),
          :fromGroup => Group,
          :fromUser => UserInformation,
          :modifiedDate => String.t(),
          :modifiedUser => UserInformation,
          :toFolder => Folder,
          :toUser => UserInformation
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.EnvelopeTransferRule do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:fromGroup, :struct, DocuSign.Model.Group, options)
    |> deserialize(:fromUser, :struct, DocuSign.Model.UserInformation, options)
    |> deserialize(:modifiedUser, :struct, DocuSign.Model.UserInformation, options)
    |> deserialize(:toFolder, :struct, DocuSign.Model.Folder, options)
    |> deserialize(:toUser, :struct, DocuSign.Model.UserInformation, options)
  end
end
