# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.FavoriteTemplatesContentItem do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :errorDetails,
    :favoritedDate,
    :templateId
  ]

  @type t :: %__MODULE__{
          :errorDetails => ErrorDetails,
          :favoritedDate => String.t(),
          :templateId => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.FavoriteTemplatesContentItem do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:errorDetails, :struct, DocuSign.Model.ErrorDetails, options)
  end
end
