# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.GraphicsContext do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :fillColor,
    :lineColor,
    :lineWeight
  ]

  @type t :: %__MODULE__{
          :fillColor => String.t(),
          :lineColor => String.t(),
          :lineWeight => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.GraphicsContext do
  def decode(value, _options) do
    value
  end
end
