# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.GroupInformation do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :endPosition,
    :groups,
    :nextUri,
    :previousUri,
    :resultSetSize,
    :startPosition,
    :totalSetSize
  ]

  @type t :: %__MODULE__{
          :endPosition => String.t(),
          :groups => [Group],
          :nextUri => String.t(),
          :previousUri => String.t(),
          :resultSetSize => String.t(),
          :startPosition => String.t(),
          :totalSetSize => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.GroupInformation do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:groups, :list, DocuSign.Model.Group, options)
  end
end
