# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.IdCheckSecurityStep do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :authType
  ]

  @type t :: %__MODULE__{
          :authType => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.IdCheckSecurityStep do
  def decode(value, _options) do
    value
  end
end
