# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.IdentityVerifications do
  @moduledoc """
  Identity Verification enables you to verify a signer&#39;s identity before they can access a document. The &#x60;IdentityVerifications&#x60; resource provides a method that enables you to list the workflows that are available to an account.
  """

  @derive [Poison.Encoder]
  defstruct [
    :identityVerification
  ]

  @type t :: %__MODULE__{
          :identityVerification => [AccountIdentityVerificationWorkflow]
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.IdentityVerifications do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :identityVerification,
      :list,
      DocuSign.Model.AccountIdentityVerificationWorkflow,
      options
    )
  end
end
