# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.LocalePolicyTab do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :addressFormat,
    :calendarType,
    :cultureName,
    :currencyCode,
    :currencyNegativeFormat,
    :currencyPositiveFormat,
    :customDateFormat,
    :customTimeFormat,
    :dateFormat,
    :initialFormat,
    :nameFormat,
    :timeFormat,
    :timeZone
  ]

  @type t :: %__MODULE__{
          :addressFormat => String.t(),
          :calendarType => String.t(),
          :cultureName => String.t(),
          :currencyCode => String.t(),
          :currencyNegativeFormat => String.t(),
          :currencyPositiveFormat => String.t(),
          :customDateFormat => String.t(),
          :customTimeFormat => String.t(),
          :dateFormat => String.t(),
          :initialFormat => String.t(),
          :nameFormat => String.t(),
          :timeFormat => String.t(),
          :timeZone => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.LocalePolicyTab do
  def decode(value, _options) do
    value
  end
end
