# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.NewAccountDefinition do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :accountName,
    :accountSettings,
    :addressInformation,
    :creditCardInformation,
    :directDebitProcessorInformation,
    :distributorCode,
    :distributorPassword,
    :envelopePartitionId,
    :initialUser,
    :paymentMethod,
    :paymentProcessorInformation,
    :planInformation,
    :referralInformation,
    :socialAccountInformation
  ]

  @type t :: %__MODULE__{
          :accountName => String.t(),
          :accountSettings => AccountSettingsInformation,
          :addressInformation => AccountAddress,
          :creditCardInformation => CreditCardInformation,
          :directDebitProcessorInformation => DirectDebitProcessorInformation,
          :distributorCode => String.t(),
          :distributorPassword => String.t(),
          :envelopePartitionId => String.t(),
          :initialUser => UserInformation,
          :paymentMethod => String.t(),
          :paymentProcessorInformation => PaymentProcessorInformation,
          :planInformation => PlanInformation,
          :referralInformation => ReferralInformation,
          :socialAccountInformation => SocialAccountInformation
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.NewAccountDefinition do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :accountSettings,
      :struct,
      DocuSign.Model.AccountSettingsInformation,
      options
    )
    |> deserialize(:addressInformation, :struct, DocuSign.Model.AccountAddress, options)
    |> deserialize(
      :creditCardInformation,
      :struct,
      DocuSign.Model.CreditCardInformation,
      options
    )
    |> deserialize(
      :directDebitProcessorInformation,
      :struct,
      DocuSign.Model.DirectDebitProcessorInformation,
      options
    )
    |> deserialize(:initialUser, :struct, DocuSign.Model.UserInformation, options)
    |> deserialize(
      :paymentProcessorInformation,
      :struct,
      DocuSign.Model.PaymentProcessorInformation,
      options
    )
    |> deserialize(:planInformation, :struct, DocuSign.Model.PlanInformation, options)
    |> deserialize(
      :referralInformation,
      :struct,
      DocuSign.Model.ReferralInformation,
      options
    )
    |> deserialize(
      :socialAccountInformation,
      :struct,
      DocuSign.Model.SocialAccountInformation,
      options
    )
  end
end
