# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.NotaryJurisdiction do
  @moduledoc """
  Creating, updating, and deleting notary jurisdiction objects.
  """

  @derive [Poison.Encoder]
  defstruct [
    :commissionExpiration,
    :commissionId,
    :county,
    :errorDetails,
    :jurisdiction,
    :registeredName,
    :sealType
  ]

  @type t :: %__MODULE__{
          :commissionExpiration => String.t(),
          :commissionId => String.t(),
          :county => String.t(),
          :errorDetails => ErrorDetails,
          :jurisdiction => Jurisdiction,
          :registeredName => String.t(),
          :sealType => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.NotaryJurisdiction do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:errorDetails, :struct, DocuSign.Model.ErrorDetails, options)
    |> deserialize(:jurisdiction, :struct, DocuSign.Model.Jurisdiction, options)
  end
end
