# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.NotificationDefaults do
  @moduledoc """
  The &#x60;NotificationDefaults&#x60; resource provides methods that enable you to manage the default notifications for envelopes.
  """

  @derive [Poison.Encoder]
  defstruct [
    :apiEmailNotifications,
    :emailNotifications
  ]

  @type t :: %__MODULE__{
          :apiEmailNotifications => NotificationDefaultSettings,
          :emailNotifications => NotificationDefaultSettings
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.NotificationDefaults do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :apiEmailNotifications,
      :struct,
      DocuSign.Model.NotificationDefaultSettings,
      options
    )
    |> deserialize(
      :emailNotifications,
      :struct,
      DocuSign.Model.NotificationDefaultSettings,
      options
    )
  end
end
