# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.NotificationDefaultSettings do
  @moduledoc """
  Contains details about the default notification settings for the envelope notifications that senders and signers receive.
  """

  @derive [Poison.Encoder]
  defstruct [
    :senderEmailNotifications,
    :signerEmailNotifications
  ]

  @type t :: %__MODULE__{
          :senderEmailNotifications => SenderEmailNotifications,
          :signerEmailNotifications => SignerEmailNotifications
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.NotificationDefaultSettings do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :senderEmailNotifications,
      :struct,
      DocuSign.Model.SenderEmailNotifications,
      options
    )
    |> deserialize(
      :signerEmailNotifications,
      :struct,
      DocuSign.Model.SignerEmailNotifications,
      options
    )
  end
end
