# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.ProofServiceViewLink do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ViewLink
  ]

  @type t :: %__MODULE__{
          :ViewLink => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.ProofServiceViewLink do
  def decode(value, _options) do
    value
  end
end
