# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.RecipientUpdateResponse do
  @moduledoc """
  The recipient details that are returned after you update the recipient.
  """

  @derive [Poison.Encoder]
  defstruct [
    :combined,
    :errorDetails,
    :recipientId,
    :recipientIdGuid,
    :tabs
  ]

  @type t :: %__MODULE__{
          :combined => String.t(),
          :errorDetails => ErrorDetails,
          :recipientId => String.t(),
          :recipientIdGuid => String.t(),
          :tabs => EnvelopeRecipientTabs
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.RecipientUpdateResponse do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:errorDetails, :struct, DocuSign.Model.ErrorDetails, options)
    |> deserialize(:tabs, :struct, DocuSign.Model.EnvelopeRecipientTabs, options)
  end
end
