# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.RecipientRouting do
  @moduledoc """
  Describes the recipient routing rules.
  """

  @derive [Poison.Encoder]
  defstruct [
    :rules
  ]

  @type t :: %__MODULE__{
          :rules => RecipientRules
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.RecipientRouting do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:rules, :struct, DocuSign.Model.RecipientRules, options)
  end
end
