# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.RecipientEmailNotification do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :emailBody,
    :emailBodyMetadata,
    :emailSubject,
    :emailSubjectMetadata,
    :supportedLanguage,
    :supportedLanguageMetadata
  ]

  @type t :: %__MODULE__{
          :emailBody => String.t(),
          :emailBodyMetadata => PropertyMetadata,
          :emailSubject => String.t(),
          :emailSubjectMetadata => PropertyMetadata,
          :supportedLanguage => String.t(),
          :supportedLanguageMetadata => PropertyMetadata
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.RecipientEmailNotification do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:emailBodyMetadata, :struct, DocuSign.Model.PropertyMetadata, options)
    |> deserialize(
      :emailSubjectMetadata,
      :struct,
      DocuSign.Model.PropertyMetadata,
      options
    )
    |> deserialize(
      :supportedLanguageMetadata,
      :struct,
      DocuSign.Model.PropertyMetadata,
      options
    )
  end
end
