# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.RecipientFormData do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :DeclinedTime,
    :DeliveredTime,
    :email,
    :formData,
    :name,
    :recipientId,
    :SentTime,
    :SignedTime
  ]

  @type t :: %__MODULE__{
          :DeclinedTime => String.t(),
          :DeliveredTime => String.t(),
          :email => String.t(),
          :formData => [FormDataItem],
          :name => String.t(),
          :recipientId => String.t(),
          :SentTime => String.t(),
          :SignedTime => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.RecipientFormData do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:formData, :list, DocuSign.Model.FormDataItem, options)
  end
end
