# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.RecipientAdditionalNotification do
  @moduledoc """
  Describes an additional notification method.
  """

  @derive [Poison.Encoder]
  defstruct [
    :phoneNumber,
    :secondaryDeliveryMethod,
    :secondaryDeliveryMethodMetadata,
    :secondaryDeliveryStatus
  ]

  @type t :: %__MODULE__{
          :phoneNumber => RecipientPhoneNumber,
          :secondaryDeliveryMethod => String.t(),
          :secondaryDeliveryMethodMetadata => PropertyMetadata,
          :secondaryDeliveryStatus => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.RecipientAdditionalNotification do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:phoneNumber, :struct, DocuSign.Model.RecipientPhoneNumber, options)
    |> deserialize(
      :secondaryDeliveryMethodMetadata,
      :struct,
      DocuSign.Model.PropertyMetadata,
      options
    )
  end
end
