# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.ReportInProductRunResponseRow do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :envelopeId,
    :fields
  ]

  @type t :: %__MODULE__{
          :envelopeId => String.t(),
          :fields => ReportInProductRunResponseRowFields
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.ReportInProductRunResponseRow do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :fields,
      :struct,
      DocuSign.Model.ReportInProductRunResponseRowFields,
      options
    )
  end
end
