# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.ServiceInformation do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :buildBranch,
    :buildBranchDeployedDateTime,
    :buildSHA,
    :buildVersion,
    :linkedSites,
    :serviceVersions
  ]

  @type t :: %__MODULE__{
          :buildBranch => String.t(),
          :buildBranchDeployedDateTime => String.t(),
          :buildSHA => String.t(),
          :buildVersion => String.t(),
          :linkedSites => [String.t()],
          :serviceVersions => [ServiceVersion]
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.ServiceInformation do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:serviceVersions, :list, DocuSign.Model.ServiceVersion, options)
  end
end
