# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.SignatureGroupDef do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :groupId,
    :rights
  ]

  @type t :: %__MODULE__{
          :groupId => String.t(),
          :rights => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.SignatureGroupDef do
  def decode(value, _options) do
    value
  end
end
