# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.SigningGroup do
  @moduledoc """
  Contains details about a signing group. Signing groups enable you to send an envelope to a predefined group of recipients and have any one member of the group sign your documents. When you send an envelope to a signing group, anyone in the group can open it and sign it with their own signature.
  """

  @derive [Poison.Encoder]
  defstruct [
    :created,
    :createdBy,
    :errorDetails,
    :groupEmail,
    :groupName,
    :groupType,
    :modified,
    :modifiedBy,
    :signingGroupId,
    :users
  ]

  @type t :: %__MODULE__{
          :created => String.t(),
          :createdBy => String.t(),
          :errorDetails => ErrorDetails,
          :groupEmail => String.t(),
          :groupName => String.t(),
          :groupType => String.t(),
          :modified => String.t(),
          :modifiedBy => String.t(),
          :signingGroupId => String.t(),
          :users => [SigningGroupUser]
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.SigningGroup do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:errorDetails, :struct, DocuSign.Model.ErrorDetails, options)
    |> deserialize(:users, :list, DocuSign.Model.SigningGroupUser, options)
  end
end
