# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.TabAccountSettings do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :allowTabOrder,
    :allowTabOrderMetadata,
    :approveDeclineTabsEnabled,
    :approveDeclineTabsMetadata,
    :calculatedFieldsEnabled,
    :calculatedFieldsMetadata,
    :checkboxTabsEnabled,
    :checkBoxTabsMetadata,
    :dataFieldRegexEnabled,
    :dataFieldRegexMetadata,
    :dataFieldSizeEnabled,
    :dataFieldSizeMetadata,
    :drawTabsEnabled,
    :drawTabsMetadata,
    :firstLastEmailTabsEnabled,
    :firstLastEmailTabsMetadata,
    :listTabsEnabled,
    :listTabsMetadata,
    :noteTabsEnabled,
    :noteTabsMetadata,
    :prefillTabsEnabled,
    :prefillTabsMetadata,
    :radioTabsEnabled,
    :radioTabsMetadata,
    :savingCustomTabsEnabled,
    :savingCustomTabsMetadata,
    :senderToChangeTabAssignmentsEnabled,
    :senderToChangeTabAssignmentsMetadata,
    :sharedCustomTabsEnabled,
    :sharedCustomTabsMetadata,
    :tabDataLabelEnabled,
    :tabDataLabelMetadata,
    :tabLocationEnabled,
    :tabLocationMetadata,
    :tabLockingEnabled,
    :tabLockingMetadata,
    :tabScaleEnabled,
    :tabScaleMetadata,
    :tabTextFormattingEnabled,
    :tabTextFormattingMetadata,
    :textTabsEnabled,
    :textTabsMetadata
  ]

  @type t :: %__MODULE__{
          :allowTabOrder => String.t(),
          :allowTabOrderMetadata => SettingsMetadata,
          :approveDeclineTabsEnabled => String.t(),
          :approveDeclineTabsMetadata => SettingsMetadata,
          :calculatedFieldsEnabled => String.t(),
          :calculatedFieldsMetadata => SettingsMetadata,
          :checkboxTabsEnabled => String.t(),
          :checkBoxTabsMetadata => SettingsMetadata,
          :dataFieldRegexEnabled => String.t(),
          :dataFieldRegexMetadata => SettingsMetadata,
          :dataFieldSizeEnabled => String.t(),
          :dataFieldSizeMetadata => SettingsMetadata,
          :drawTabsEnabled => String.t(),
          :drawTabsMetadata => SettingsMetadata,
          :firstLastEmailTabsEnabled => String.t(),
          :firstLastEmailTabsMetadata => SettingsMetadata,
          :listTabsEnabled => String.t(),
          :listTabsMetadata => SettingsMetadata,
          :noteTabsEnabled => String.t(),
          :noteTabsMetadata => SettingsMetadata,
          :prefillTabsEnabled => String.t(),
          :prefillTabsMetadata => SettingsMetadata,
          :radioTabsEnabled => String.t(),
          :radioTabsMetadata => SettingsMetadata,
          :savingCustomTabsEnabled => String.t(),
          :savingCustomTabsMetadata => SettingsMetadata,
          :senderToChangeTabAssignmentsEnabled => String.t(),
          :senderToChangeTabAssignmentsMetadata => SettingsMetadata,
          :sharedCustomTabsEnabled => String.t(),
          :sharedCustomTabsMetadata => SettingsMetadata,
          :tabDataLabelEnabled => String.t(),
          :tabDataLabelMetadata => SettingsMetadata,
          :tabLocationEnabled => String.t(),
          :tabLocationMetadata => SettingsMetadata,
          :tabLockingEnabled => String.t(),
          :tabLockingMetadata => SettingsMetadata,
          :tabScaleEnabled => String.t(),
          :tabScaleMetadata => SettingsMetadata,
          :tabTextFormattingEnabled => String.t(),
          :tabTextFormattingMetadata => SettingsMetadata,
          :textTabsEnabled => String.t(),
          :textTabsMetadata => SettingsMetadata
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.TabAccountSettings do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :allowTabOrderMetadata,
      :struct,
      DocuSign.Model.SettingsMetadata,
      options
    )
    |> deserialize(
      :approveDeclineTabsMetadata,
      :struct,
      DocuSign.Model.SettingsMetadata,
      options
    )
    |> deserialize(
      :calculatedFieldsMetadata,
      :struct,
      DocuSign.Model.SettingsMetadata,
      options
    )
    |> deserialize(
      :checkBoxTabsMetadata,
      :struct,
      DocuSign.Model.SettingsMetadata,
      options
    )
    |> deserialize(
      :dataFieldRegexMetadata,
      :struct,
      DocuSign.Model.SettingsMetadata,
      options
    )
    |> deserialize(
      :dataFieldSizeMetadata,
      :struct,
      DocuSign.Model.SettingsMetadata,
      options
    )
    |> deserialize(:drawTabsMetadata, :struct, DocuSign.Model.SettingsMetadata, options)
    |> deserialize(
      :firstLastEmailTabsMetadata,
      :struct,
      DocuSign.Model.SettingsMetadata,
      options
    )
    |> deserialize(:listTabsMetadata, :struct, DocuSign.Model.SettingsMetadata, options)
    |> deserialize(:noteTabsMetadata, :struct, DocuSign.Model.SettingsMetadata, options)
    |> deserialize(:prefillTabsMetadata, :struct, DocuSign.Model.SettingsMetadata, options)
    |> deserialize(:radioTabsMetadata, :struct, DocuSign.Model.SettingsMetadata, options)
    |> deserialize(
      :savingCustomTabsMetadata,
      :struct,
      DocuSign.Model.SettingsMetadata,
      options
    )
    |> deserialize(
      :senderToChangeTabAssignmentsMetadata,
      :struct,
      DocuSign.Model.SettingsMetadata,
      options
    )
    |> deserialize(
      :sharedCustomTabsMetadata,
      :struct,
      DocuSign.Model.SettingsMetadata,
      options
    )
    |> deserialize(
      :tabDataLabelMetadata,
      :struct,
      DocuSign.Model.SettingsMetadata,
      options
    )
    |> deserialize(:tabLocationMetadata, :struct, DocuSign.Model.SettingsMetadata, options)
    |> deserialize(:tabLockingMetadata, :struct, DocuSign.Model.SettingsMetadata, options)
    |> deserialize(:tabScaleMetadata, :struct, DocuSign.Model.SettingsMetadata, options)
    |> deserialize(
      :tabTextFormattingMetadata,
      :struct,
      DocuSign.Model.SettingsMetadata,
      options
    )
    |> deserialize(:textTabsMetadata, :struct, DocuSign.Model.SettingsMetadata, options)
  end
end
