# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.TemplateResponsiveHtmlPreview do
  @moduledoc """
  This resource is used to create a responsive preview of all of the documents associated with a template.
  """

  @derive [Poison.Encoder]
  defstruct [
    :htmlDefinitions
  ]

  @type t :: %__MODULE__{
          :htmlDefinitions => [String.t()]
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.TemplateResponsiveHtmlPreview do
  def decode(value, _options) do
    value
  end
end
