# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.UserInformation do
  @moduledoc """
  User information.
  """

  @derive [Poison.Encoder]
  defstruct [
    :activationAccessCode,
    :company,
    :connectConfigurations,
    :countryCode,
    :createdDateTime,
    :customSettings,
    :defaultAccountId,
    :email,
    :enableConnectForUser,
    :errorDetails,
    :firstName,
    :forgottenPasswordInfo,
    :groupList,
    :hasRemoteNotary,
    :homeAddress,
    :initialsImageUri,
    :isAdmin,
    :isNAREnabled,
    :jobTitle,
    :lastLogin,
    :lastName,
    :loginStatus,
    :middleName,
    :password,
    :passwordExpiration,
    :permissionProfileId,
    :permissionProfileName,
    :profileImageUri,
    :sendActivationEmail,
    :sendActivationOnInvalidLogin,
    :signatureImageUri,
    :subscribe,
    :suffixName,
    :title,
    :uri,
    :userAddedToAccountDateTime,
    :userId,
    :userName,
    :userProfileLastModifiedDate,
    :userSettings,
    :userStatus,
    :userType,
    :workAddress
  ]

  @type t :: %__MODULE__{
          :activationAccessCode => String.t(),
          :company => String.t(),
          :connectConfigurations => [ConnectUserObject],
          :countryCode => String.t(),
          :createdDateTime => String.t(),
          :customSettings => [NameValue],
          :defaultAccountId => String.t(),
          :email => String.t(),
          :enableConnectForUser => String.t(),
          :errorDetails => ErrorDetails,
          :firstName => String.t(),
          :forgottenPasswordInfo => ForgottenPasswordInformation,
          :groupList => [Group],
          :hasRemoteNotary => boolean(),
          :homeAddress => AddressInformation,
          :initialsImageUri => String.t(),
          :isAdmin => String.t(),
          :isNAREnabled => String.t(),
          :jobTitle => String.t(),
          :lastLogin => String.t(),
          :lastName => String.t(),
          :loginStatus => String.t(),
          :middleName => String.t(),
          :password => String.t(),
          :passwordExpiration => String.t(),
          :permissionProfileId => String.t(),
          :permissionProfileName => String.t(),
          :profileImageUri => String.t(),
          :sendActivationEmail => String.t(),
          :sendActivationOnInvalidLogin => String.t(),
          :signatureImageUri => String.t(),
          :subscribe => String.t(),
          :suffixName => String.t(),
          :title => String.t(),
          :uri => String.t(),
          :userAddedToAccountDateTime => String.t(),
          :userId => String.t(),
          :userName => String.t(),
          :userProfileLastModifiedDate => String.t(),
          :userSettings => UserSettingsInformation,
          :userStatus => String.t(),
          :userType => String.t(),
          :workAddress => AddressInformation
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.UserInformation do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :connectConfigurations,
      :list,
      DocuSign.Model.ConnectUserObject,
      options
    )
    |> deserialize(:customSettings, :list, DocuSign.Model.NameValue, options)
    |> deserialize(:errorDetails, :struct, DocuSign.Model.ErrorDetails, options)
    |> deserialize(
      :forgottenPasswordInfo,
      :struct,
      DocuSign.Model.ForgottenPasswordInformation,
      options
    )
    |> deserialize(:groupList, :list, DocuSign.Model.Group, options)
    |> deserialize(:homeAddress, :struct, DocuSign.Model.AddressInformation, options)
    |> deserialize(:userSettings, :struct, DocuSign.Model.UserSettingsInformation, options)
    |> deserialize(:workAddress, :struct, DocuSign.Model.AddressInformation, options)
  end
end
