# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.WorkspaceSettings do
  @moduledoc """
  This object provides information about the settings for the workspace.
  """

  @derive [Poison.Encoder]
  defstruct [
    :commentsAllowed
  ]

  @type t :: %__MODULE__{
          :commentsAllowed => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.WorkspaceSettings do
  def decode(value, _options) do
    value
  end
end
