# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.Workspace do
  @moduledoc """
  A DocuSign workspace is a collaboration area for sharing files and data.
  """

  @derive [Poison.Encoder]
  defstruct [
    :billableAccountId,
    :callerInformation,
    :created,
    :createdByInformation,
    :lastModified,
    :lastModifiedByInformation,
    :settings,
    :status,
    :workspaceBaseUrl,
    :workspaceDescription,
    :workspaceId,
    :workspaceName,
    :workspaceUri
  ]

  @type t :: %__MODULE__{
          :billableAccountId => String.t(),
          :callerInformation => WorkspaceUser,
          :created => String.t(),
          :createdByInformation => WorkspaceUser,
          :lastModified => String.t(),
          :lastModifiedByInformation => WorkspaceUser,
          :settings => WorkspaceSettings,
          :status => String.t(),
          :workspaceBaseUrl => String.t(),
          :workspaceDescription => String.t(),
          :workspaceId => String.t(),
          :workspaceName => String.t(),
          :workspaceUri => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.Workspace do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:callerInformation, :struct, DocuSign.Model.WorkspaceUser, options)
    |> deserialize(:createdByInformation, :struct, DocuSign.Model.WorkspaceUser, options)
    |> deserialize(
      :lastModifiedByInformation,
      :struct,
      DocuSign.Model.WorkspaceUser,
      options
    )
    |> deserialize(:settings, :struct, DocuSign.Model.WorkspaceSettings, options)
  end
end
