# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Model.WorkflowStep do
  @moduledoc """
  Describes a single step in a workflow.
  """

  @derive [Poison.Encoder]
  defstruct [
    :action,
    :completedDate,
    :itemId,
    :recipientRouting,
    :status,
    :triggeredDate,
    :triggerOnItem,
    :workflowStepId
  ]

  @type t :: %__MODULE__{
          :action => String.t(),
          :completedDate => String.t(),
          :itemId => String.t(),
          :recipientRouting => RecipientRouting,
          :status => String.t(),
          :triggeredDate => String.t(),
          :triggerOnItem => String.t(),
          :workflowStepId => String.t()
        }
end

defimpl Poison.Decoder, for: DocuSign.Model.WorkflowStep do
  import DocuSign.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:recipientRouting, :struct, DocuSign.Model.RecipientRouting, options)
  end
end
