# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DocuSign.Api.BCCEmailArchive do
  @moduledoc """
  API calls for all endpoints tagged `BCCEmailArchive`.
  """

  alias DocuSign.Connection
  import DocuSign.RequestBuilder

  @doc """
  Deletes a BCC email archive configuration.
  This method deletes a BCC email archive configuration from an account.  When you use this method, the status of the BCC email archive configuration switches to &#x60;closed&#x60; and the BCC email address is no longer used to archive DocuSign-generated email messages.

  ## Parameters

  - connection (DocuSign.Connection): Connection to server
  - account_id (String.t): The external account number (int) or account ID GUID.
  - bcc_email_archive_id (String.t): The id of the BCC email archive configuration.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec bcc_email_archive_delete_bcc_email_archive(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          keyword()
        ) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def bcc_email_archive_delete_bcc_email_archive(
        connection,
        account_id,
        bcc_email_archive_id,
        _opts \\ []
      ) do
    %{}
    |> method(:delete)
    |> url("/v2.1/accounts/#{account_id}/settings/bcc_email_archives/#{bcc_email_archive_id}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end

  @doc """
  Gets a BCC email archive configuration and its history.
  This method returns a specific BCC email archive configuration for an account, as well as the history of changes to the email address.

  ## Parameters

  - connection (DocuSign.Connection): Connection to server
  - account_id (String.t): The external account number (int) or account ID GUID.
  - bcc_email_archive_id (String.t): The id of the BCC email archive configuration.
  - opts (KeywordList): [optional] Optional parameters
    - :count (String.t): (Optional) The maximum number of results (changes) to return.
    - :start_position (String.t): (Optional) The index position within the total result set from which to start returning values. The default value is &#x60;0&#x60;.

  ## Returns

  {:ok, %DocuSign.Model.BccEmailArchiveHistoryList{}} on success
  {:error, info} on failure
  """
  @spec bcc_email_archive_get_bcc_email_archive_history_list(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          keyword()
        ) :: {:ok, DocuSign.Model.BccEmailArchiveHistoryList.t()} | {:error, Tesla.Env.t()}
  def bcc_email_archive_get_bcc_email_archive_history_list(
        connection,
        account_id,
        bcc_email_archive_id,
        opts \\ []
      ) do
    optional_params = %{
      :count => :query,
      :start_position => :query
    }

    %{}
    |> method(:get)
    |> url("/v2.1/accounts/#{account_id}/settings/bcc_email_archives/#{bcc_email_archive_id}")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%DocuSign.Model.BccEmailArchiveHistoryList{})
  end

  @doc """
  Gets the BCC email archive configurations for an account.
  This method retrieves all of the BCC email archive configurations associated with an account.

  ## Parameters

  - connection (DocuSign.Connection): Connection to server
  - account_id (String.t): The external account number (int) or account ID GUID.
  - opts (KeywordList): [optional] Optional parameters
    - :count (String.t): (Optional) The maximum number of results to return.
    - :start_position (String.t): (Optional) The index position within the total result set from which to start returning values. The default value is &#x60;0&#x60;.

  ## Returns

  {:ok, %DocuSign.Model.BccEmailArchiveList{}} on success
  {:error, info} on failure
  """
  @spec bcc_email_archive_get_bcc_email_archive_list(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, DocuSign.Model.BccEmailArchiveList.t()} | {:error, Tesla.Env.t()}
  def bcc_email_archive_get_bcc_email_archive_list(connection, account_id, opts \\ []) do
    optional_params = %{
      :count => :query,
      :start_position => :query
    }

    %{}
    |> method(:get)
    |> url("/v2.1/accounts/#{account_id}/settings/bcc_email_archives")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%DocuSign.Model.BccEmailArchiveList{})
  end

  @doc """
  Creates a BCC email archive configuration.
  This method creates a BCC email archive configuration for an account (adds a BCC email address to the account for archiving the emails that DocuSign generates).  The only property that you must set in the request body is the BCC email address that you want to use.  **Note**: An account can have up to five active and pending email archive addresses combined, but you must use this method to add them to the account one at a time. Each email address is considered a separate BCC email archive configuration.

  ## Parameters

  - connection (DocuSign.Connection): Connection to server
  - account_id (String.t): The external account number (int) or account ID GUID.
  - opts (KeywordList): [optional] Optional parameters
    - :bcc_email_archive (BccEmailArchive): Boolean that specifies whether BCC for Email Archive is enabled for the account. BCC for Email Archive allows you to set up an archive email address so that a BCC copy of an envelope is sent only to that address.

  ## Returns

  {:ok, %DocuSign.Model.BccEmailArchive{}} on success
  {:error, info} on failure
  """
  @spec bcc_email_archive_post_bcc_email_archive(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, DocuSign.Model.BccEmailArchive.t()} | {:error, Tesla.Env.t()}
  def bcc_email_archive_post_bcc_email_archive(connection, account_id, opts \\ []) do
    optional_params = %{
      :bccEmailArchive => :body
    }

    %{}
    |> method(:post)
    |> url("/v2.1/accounts/#{account_id}/settings/bcc_email_archives")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%DocuSign.Model.BccEmailArchive{})
  end
end
